FROM php:8.2-cli

# Instalar extensiones necesarias
RUN docker-php-ext-install pdo pdo_mysql

# Instalar Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

# Copiar archivos
COPY . .

# Instalar dependencias
RUN composer install

# Exponer puerto
EXPOSE 8000

# Comando para iniciar servidor
CMD php artisan serve --host=0.0.0.0 --port=8000